[config]

[config.wallpaper]
command = "swww"
# Apply to every detected output; swww otherwise targets only the focused one.
arguments = ["img", "--outputs", "all", "--transition-type", "wave", "--transition-step", "10", "--transition-angle", "45", "--transition-duration", "2", "--transition-fps", "144"]
set = true

[templates.rofi]
input_path = "./templates/rofi.rasi"
output_path = "~/.config/rofi/colors/matugen.rasi"

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '../kitty/themes/matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.gtk3]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5]
input_path = './templates/qt.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6]
input_path = './templates/qt.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/config'
# post_hook = "pkill -USR1 cava"  # uncomment if cava is running

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.hyprland]
input_path = './templates/hypr.conf'
output_path = '../hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.hyprlock]
input_path = './templates/hyprlock.conf'
output_path = '../hypr/hyprlock.conf'

[templates.waybar]
input_path = './templates/waybar.css'
output_path = '~/.config/waybar/style.css'
post_hook = './.config/waybar/scripts/launch-waybar.sh'

[templates.swaync]
input_path = './templates/swaync.css'
output_path = '~/.config/swaync/style.css'
post_hook = 'swaync-client -rs'

[templates.swayosd]
input_path = './templates/swayosd.css'
output_path = '~/.config/swayosd/style.css'
post_hook = 'pkill swayosd-server 2>/dev/null; sleep 0.3; nohup swayosd-server > /dev/null 2>&1 &'

[templates.obsidian]
input_path = './templates/obsidian.css'
output_path = '~/Projects/Notes/.obsidian/snippets/matugen.css'

[templates.zen]
input_path = './templates/zen.css'
output_path = '~/.zen/icbf5wlx.Default (release)/chrome/matugen.css'

[templates.nvim]
input_path = "./templates/nvim.lua"
output_path = "~/.cache/wal/base46-dark.lua"
post_hook = "mkdir -p ~/.local/share/nvim/lazy/base46/lua/base46/themes && ln -sf ~/.cache/wal/base46-dark.lua ~/.local/share/nvim/lazy/base46/lua/base46/themes/chadwal.lua"

[templates.nvimlight]
input_path = "./templates/nvim.lua"
output_path = "~/.cache/wal/base46-light.lua"
post_hook = "mkdir -p ~/.local/share/nvim/lazy/base46/lua/base46/themes && ln -sf ~/.cache/wal/base46-light.lua ~/.local/share/nvim/lazy/base46/lua/base46/themes/chadwal-light.lua"

[templates.discord]
input_path = './templates/midnight-discord.css'
output_path = '~/.config/Vencord/themes/midnight-discord.css'

[templates.discord-flatpak]
input_path = './templates/midnight-discord.css'
output_path = '~/.var/app/com.discordapp.Discord/config/Vencord/themes/midnight-discord.css'

[templates.yazi]
input_path = "./templates/yazi.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.spicetify-color]
input_path = './templates/spicetify-color.ini'
output_path = '~/.config/spicetify/Themes/matugen/color.ini'

[templates.spicetify-css]
input_path = './templates/spicetify-user.css'
output_path = '~/.config/spicetify/Themes/matugen/user.css'

[templates.spicetify-dribbblish]
input_path = './templates/spicetify-dribbblish.ini'
output_path = '~/.config/spicetify/Themes/Dribbblish/color.ini'
post_hook = './scripts/spicetify.sh'

[templates.vesktop]
input_path = './templates/vesktop-midnight-discord.css'
output_path = '~/.var/app/dev.vencord.Vesktop/config/vesktop/themes/themes.css'

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true