[config]

[config.wallpaper]
command = "swww"
# Apply to every detected output; swww otherwise targets only the focused one.
arguments = ["img", "--outputs", "all", "--transition-type", "wave", "--transition-step", "20", "--transition-angle", "45", "--transition-duration", "0.5", "--transition-fps", "60"]
# Disabled - waypaper already sets wallpaper via swww backend
set = false

[templates.gtk3]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.rofi]
input_path = "./templates/rofi.rasi"
output_path = "~/.config/rofi/colors/matugen.rasi"

[templates.rofi-screenshot]
input_path = "./templates/screenshot-gnome.rasi"
output_path = "~/.config/rofi/screenshot-gnome.rasi"

[templates.rofi-search]
input_path = "./templates/rofi-search.rasi"
output_path = "~/.config/rofi/search/colors-matugen.rasi"

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '../kitty/themes/matugen.conf'

[templates.tty-clock]
input_path = "./templates/tty-clock-wrapper.sh"
output_path = "~/.local/bin/tty-clock-themed"

[templates.qt5]
input_path = './templates/qt.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6]
input_path = './templates/qt.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/config'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.hyprland]
input_path = './templates/hypr.conf'
output_path = '../hypr/colors.conf'

[templates.hyprlock]
input_path = './templates/hyprlock.conf'
output_path = '../hypr/hyprlock.conf'

[templates.waybar]
input_path = './templates/waybar.css'
output_path = '~/.config/waybar/style.css'

[templates.mako]
input_path = './templates/mako.conf'
output_path = '~/.config/mako/config'

[templates.obsidian]
input_path = './templates/obsidian.css'
output_path = '~/Projects/Notes/.obsidian/snippets/matugen.css'

[templates.nvim]
input_path = "./templates/nvim-lazyvim.lua"
output_path = "~/.config/nvim/colors/matugen.lua"

# Light theme disabled - uncomment if needed
# [templates.nvimlight]
# input_path = "./templates/nvim-lazyvim.lua"
# output_path = "~/.config/nvim/colors/matugen-light.lua"

[templates.yazi]
input_path = "./templates/yazi.toml"
output_path = "~/.config/yazi/theme.toml"

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
