[config]

# [config.wallpaper]
# command = "swww"
# arguments = ["img", "--transition-type", "center"]
# set = false

[templates.rofi]
input_path = "./templates/rofi.rasi"
output_path = "~/.config/rofi/colors/matugen.rasi"

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '../kitty/themes/matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.gtk3]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5]
input_path = './templates/qt.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6]
input_path = './templates/qt.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/config'
# post_hook = "pkill -USR1 cava"  # uncomment if cava is running

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.hyprland]
input_path = './templates/hypr.conf'
output_path = '../hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.hyprlock]
input_path = './templates/hyprlock.conf'
output_path = '../hypr/hyprlock.conf'

[templates.waybar]
input_path = './templates/waybar.css'
output_path = '~/.config/waybar/style.css'
post_hook = './.config/waybar/scripts/launch-waybar.sh'

[templates.swaync]
input_path = './templates/swaync.css'
output_path = '~/.config/swaync/style.css'
post_hook = 'swaync-client -rs'

[templates.swayosd]
input_path = './templates/swayosd.css'
output_path = '~/.config/swayosd/style.css'

[templates.obsidian]
input_path = './templates/obsidian.css'
output_path = '~/Projects/Notes/.obsidian/snippets/matugen.css'

[templates.zen]
input_path = './templates/zen.css'
output_path = '~/.zen/icbf5wlx.Default (release)/chrome/matugen.css'
post_hook = 'notify-send "Matugen" "Zen browser theme updated. Please restart Zen to see changes." -u normal'

[templates.nvim]
input_path = './templates/nvim.lua'
output_path = '~/.config/nvim/colors/matugen.lua'

[templates.discord]
input_path = './templates/discord.css'
output_path = '~/.config/Vencord/themes/matugen.theme.css'

[templates.discord-flatpak]
input_path = './templates/discord.css'
output_path = '~/.var/app/com.discordapp.Discord/config/Vencord/themes/matugen.theme.css'
